CONSTANT_POOL_TAGS = {
    10: "CONSTANT_Methodref",
    11: "CONSTANT_InterfaceMethodref",
    12: "CONSTANT_NameAndType",
    15: "CONSTANT_MethodHandle",
    16: "CONSTANT_MethodType",
    18: "CONSTANT_InvokeDynamic",
    1: "CONSTANT_Utf8",
    3: "CONSTANT_Integer",
    4: "CONSTANT_Float",
    5: "CONSTANT_Long",
    6: "CONSTANT_Double",
    7: "CONSTANT_Class",
    8: "CONSTANT_String",
    9: "CONSTANT_Fieldref",
}

ACCESS_FLAGS = {
    # Declared public; may be accessed from outside its package.
    "0001": "ACC_PUBLIC",
    "0010": "ACC_FINAL",  # Declared final; no subclasses allowed.
    # Treat superclass methods specially when invoked by the invokespecial instruction.
    "0020": "ACC_SUPER",
    "0200": "ACC_INTERFACE",  # Is an interface, not a class.
    "0400": "ACC_ABSTRACT",  # Declared abstract; must not be instantiated.
    # Declared synthetic; not present in the source code.
    "1000": "ACC_SYNTHETIC",
    "2000": "ACC_ANNOTATION",  # Declared as an annotation type.
    "4000": "ACC_ENUM"  # Declared as an enum type.
}

METHOD_ACCESS_FLAGS = {
    # Declared public; may be accessed from outside its package.
    "0001": "ACC_PUBLIC ",
    # Declared private; accessible only within the defining class.
    "0002": "ACC_PRIVATE ",
    # Declared protected; may be accessed within subclasses.
    "0004": "ACC_PROTECTED ",
    "0008": "ACC_STATIC ",  # Declared static.
    "0010": "ACC_FINAL ",  # Declared final; must not be overridden (§5.4.5).
    # Declared synchronized; invocation is wrapped by a monitor use.
    "0020": "ACC_SYNCHRONIZED ",
    "0040": "ACC_BRIDGE ",  # A bridge method, generated by the compiler.
    "0080": "ACC_VARARGS ",  # Declared with variable number of arguments.
    # Declared native; implemented in a language other than Java.
    "0100": "ACC_NATIVE ",
    # Declared abstract; no implementation is provided.
    "0400": "ACC_ABSTRACT ",
    # Declared strictfp; floating-point mode is FP-strict.
    "0800": "ACC_STRICT ",
    "1000": "ACC_SYNTHETIC ",  # Declared synthetic; not present in the source code
}

VERIFICATION_TYPE_INFO = {
    0: "ITEM_Top",
    1: "ITEM_Integer",
    2: "ITEM_Float",
    3: "ITEM_Double",
    4: "ITEM_Long",
    5: "ITEM_Null",
    6: "ITEM_UninitializedThis",
    7: "ITEM_Object",
    8: "ITEM_Uninitialized",
}

